# Loader metadata
modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/kimchiloof/TFC-Metallic-Compat/issues"

# TFC Metallic Compat
[[mods]]
    modId="tfc_metallic_compat"
    # The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
    # ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
    # see the associated build.gradle script for how to populate this completely automatically during a build
    version="${file.jarVersion}"
    displayName="TFC Metals+"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/tfc_metallic_compat"
    credits="Textures and base configs from/inspired by Mrthomas20121-Mods' TFC-Metallum"
    authors="Kimchiloof"
    description='''
    A compatibility mod for TerraFirmaCraft metals and other mods.
    Includes a config to enable/disable ore and metal generation for each added metal.

    Currently adds support for:
    - Aluminum
    - ...
    '''
    #logoFile="tfc_metallic_compat.png"

# Dependencies
[[dependencies.tfc_metallic_compat]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tfc_metallic_compat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tfc_metallic_compat]]
    modId="tfc"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
